$ErrorActionPreference = "Stop"
Write-Host "FarineAPP Windows production install placeholder."
Write-Host ""
Write-Host "Current production start command:"
Write-Host "  .\win-app\scripts\prod\start-server.ps1"
Write-Host ""
Write-Host "Before production, edit:"
Write-Host "  .\win-app\server\config.json"
Write-Host ""
Write-Host "Later, this script can register the Windows server as a startup task or Windows service."
